import type { Concept } from "./types"

/**
 * Concept catalog. In production this is the Knowledge Graph's shared layer,
 * enriched per-project by the Explanation Agent (`whyHere`, `usedIn`) from the System Graph.
 */
export const CONCEPTS: Record<string, Concept> = {
  postgresql: {
    id: "postgresql",
    name: "PostgreSQL",
    category: "Database",
    what: "A relational database used to persist structured application data.",
    whyHere:
      "The Authentication service stores user accounts, credential hashes and verification state in PostgreSQL because that data must survive restarts and be queried consistently.",
    usedIn: ["Authentication", "Payments", "User Management"],
    related: ["sql", "transactions", "db-index", "persistence"],
    subtopics: ["queries", "indexes", "transactions", "migrations", "replication", "partitioning", "vacuum"],
    layers: {
      happened: "Your data was saved to, or read from, the database.",
      how: "The service sends a SQL query over a pooled connection. PostgreSQL uses an index to find the row, then returns it.",
      why: "User accounts are relational (users have sessions, tokens, payments) and need ACID guarantees — a password reset must never half-apply.",
      impl: "asyncpg connection pool (min 2, max 10) via SQLAlchemy 2.0 async. `users.email` has a unique B-tree index; migrations are managed by Alembic.",
      tradeoffs: "Strong consistency and rich querying vs. horizontal write scaling. At this project's scale a single primary with read replicas is ample; sharding would add cost with no benefit.",
    },
  },
  redis: {
    id: "redis",
    name: "Redis",
    category: "Cache",
    what: "An in-memory key-value store used for caching, sessions, rate limiting and pub/sub.",
    whyHere:
      "Authentication keeps refresh-token sessions and login rate-limit counters in Redis, because they are short-lived and read on every request.",
    usedIn: ["Authentication", "Notifications"],
    related: ["caching", "rate-limiting", "refresh-tokens"],
    subtopics: ["caching", "sessions", "ttl", "pub/sub", "eviction policies", "replication", "clustering", "persistence"],
    layers: {
      happened: "The server checked a fast, temporary memory store.",
      how: "A key like `session:<id>` is read or written with a time-to-live, so it disappears automatically.",
      why: "Session lookups happen on every authenticated request; putting them in PostgreSQL would add a disk-bound query to each one.",
      impl: "redis-py asyncio client, `SET session:<id> <user_id> EX 1209600`. Rate limits use `INCR` + `EXPIRE` on `rl:login:<ip>`.",
      tradeoffs: "Microsecond reads vs. data being volatile. Losing Redis logs users out but loses no permanent data — an acceptable failure mode here.",
    },
  },
  jwt: {
    id: "jwt",
    name: "JWT",
    category: "Security",
    what: "JSON Web Token — a signed token that proves who a user is without a database lookup.",
    whyHere:
      "The mobile app sends a short-lived JWT with each API call so every service can verify the user without calling Authentication.",
    usedIn: ["Authentication", "API Gateway"],
    related: ["refresh-tokens", "password-hashing"],
    subtopics: ["claims", "signing", "expiry", "rotation", "revocation"],
    layers: {
      happened: "The server created a login token for the app.",
      how: "User id and expiry are encoded as claims and signed with a secret key. Anyone with the key can verify it wasn't tampered with.",
      why: "Stateless verification lets the gateway and services authorize requests independently, keeping Authentication off the hot path.",
      impl: "PyJWT, HS256, 15-minute `exp`, `sub` = user id, `jti` for audit. Secret from `JWT_SECRET` env var.",
      tradeoffs: "Stateless and fast vs. hard to revoke. Mitigated with a 15-minute lifetime plus revocable refresh tokens in Redis.",
    },
  },
  "password-hashing": {
    id: "password-hashing",
    name: "Password hashing",
    category: "Security",
    what: "Transforming a password into an irreversible fingerprint before storing it.",
    whyHere: "Authentication stores only bcrypt hashes in the `users` table — never the password itself.",
    usedIn: ["Authentication"],
    related: ["jwt", "postgresql"],
    subtopics: ["salting", "cost factor", "bcrypt vs argon2", "timing attacks"],
    layers: {
      happened: "The password was checked without ever being stored in readable form.",
      how: "The password is combined with a random salt and hashed many times. At login the same process runs and the results are compared.",
      why: "If the database leaks, attackers get hashes that are deliberately slow to crack instead of real passwords.",
      impl: "passlib[bcrypt], cost factor 12 (~70ms). Verification runs in a thread pool so it doesn't block the event loop.",
      tradeoffs: "Higher cost factor = safer but more CPU per login. bcrypt is the main latency contributor on /auth/login; argon2id would be stronger against GPU attacks.",
    },
  },
  fastapi: {
    id: "fastapi",
    name: "FastAPI",
    category: "Backend framework",
    what: "A Python web framework for building typed, async HTTP APIs.",
    whyHere: "The existing backend is FastAPI, so new services match it — one runtime, one set of conventions.",
    usedIn: ["Authentication", "User Management", "Notifications"],
    related: ["pydantic", "rest"],
    subtopics: ["dependency injection", "middleware", "background tasks", "ASGI", "lifespan events"],
    layers: {
      happened: "The server received the app's request and routed it to the right code.",
      how: "Each URL path maps to a Python function. FastAPI validates input, calls the function, and turns the result into JSON.",
      why: "Type hints double as validation and documentation, which keeps generated code verifiable and self-describing.",
      impl: "ASGI app on Uvicorn; Starlette middleware stack; `Depends()` builds a per-request dependency graph (db session, current user).",
      tradeoffs: "Great developer ergonomics and async I/O vs. Python's GIL for CPU work — the reason bcrypt is offloaded to a thread pool.",
    },
  },
  pydantic: {
    id: "pydantic",
    name: "Pydantic",
    category: "Validation",
    what: "A library that validates data against typed models.",
    whyHere: "Every request body in Authentication is a Pydantic model, so malformed input is rejected before business logic runs.",
    usedIn: ["Authentication", "User Management"],
    related: ["fastapi"],
    subtopics: ["validators", "serialization", "settings management"],
    layers: {
      happened: "The request was checked for missing or malformed fields.",
      how: "Incoming JSON is parsed into a typed model; invalid fields produce a 422 error listing what's wrong.",
      why: "Validating at the boundary means internal code can trust its inputs.",
      impl: "Pydantic v2 (Rust core). `EmailStr` for email, `constr(min_length=10)` for passwords.",
      tradeoffs: "Tiny per-request cost for strong guarantees; negligible compared to I/O.",
    },
  },
  rest: {
    id: "rest",
    name: "REST API",
    category: "API style",
    what: "An API style where resources are addressed by URLs and manipulated with HTTP methods.",
    whyHere: "The mobile client already talks to the backend over REST; Authentication follows the same contract.",
    usedIn: ["Authentication", "Payments", "User Management"],
    related: ["fastapi"],
    subtopics: ["status codes", "idempotency", "versioning", "pagination"],
    layers: {
      happened: "The app asked the server to do something using a web address.",
      how: "`POST /auth/login` means 'create a login session'. The status code (200, 401…) says how it went.",
      why: "REST is simple, cacheable and universally supported by mobile HTTP clients.",
      impl: "OpenAPI 3.1 schema is generated from routes and used to generate the typed React Native client.",
      tradeoffs: "Simplicity vs. over/under-fetching; GraphQL would help if screens needed many joined resources.",
    },
  },
  "email-verification": {
    id: "email-verification",
    name: "Email verification",
    category: "Security",
    what: "Confirming a user controls the email address they registered with.",
    whyHere: "Password reset sends links by email, so the address must be proven first.",
    usedIn: ["Authentication", "Notifications"],
    related: ["jwt"],
    subtopics: ["signed tokens", "expiry", "deliverability"],
    layers: {
      happened: "A confirmation link was sent to the user's inbox.",
      how: "A one-time signed token is emailed; clicking it marks the account verified.",
      why: "Prevents account takeover through typo'd or someone else's email.",
      impl: "itsdangerous URLSafeTimedSerializer, 24h expiry; sent through the Notifications service queue.",
      tradeoffs: "Extra onboarding friction vs. trustworthy recovery channel.",
    },
  },
  "refresh-tokens": {
    id: "refresh-tokens",
    name: "Refresh tokens",
    category: "Security",
    what: "Long-lived credentials used to obtain new short-lived access tokens.",
    whyHere: "Keeps mobile users logged in for 14 days while access JWTs expire every 15 minutes.",
    usedIn: ["Authentication"],
    related: ["jwt", "redis"],
    subtopics: ["rotation", "reuse detection", "revocation"],
    layers: {
      happened: "The app quietly renewed its login without asking for the password.",
      how: "The refresh token is exchanged for a new access token, and a new refresh token replaces the old one.",
      why: "Short access tokens limit damage if stolen; refresh tokens make that invisible to users.",
      impl: "Opaque 256-bit tokens stored hashed in Redis with rotation; reuse of an old token revokes the family.",
      tradeoffs: "Stateful (needs Redis) but revocable — the balance JWT alone can't give.",
    },
  },
  "rate-limiting": {
    id: "rate-limiting",
    name: "Rate limiting",
    category: "Security",
    what: "Capping how many requests a client can make in a period.",
    whyHere: "Login is limited to 5 attempts/minute per IP to slow password guessing.",
    usedIn: ["Authentication", "API Gateway"],
    related: ["redis"],
    subtopics: ["fixed window", "sliding window", "token bucket"],
    layers: {
      happened: "The server checked the caller wasn't making too many attempts.",
      how: "A counter per IP increases with each attempt and resets after a minute.",
      why: "Brute-force attacks depend on volume; limiting volume makes them impractical.",
      impl: "Redis `INCR rl:login:<ip>` + `EXPIRE 60`; 429 with `Retry-After` on breach.",
      tradeoffs: "Fixed windows allow bursts at edges; sliding windows are fairer but cost more ops.",
    },
  },
  docker: {
    id: "docker",
    name: "Docker",
    category: "Infrastructure",
    what: "Packages software and its dependencies into portable containers.",
    whyHere: "Every service, PostgreSQL and Redis run as containers via docker-compose so local runs match CI.",
    usedIn: ["Infrastructure"],
    related: [],
    subtopics: ["images", "layers", "compose", "networking", "volumes"],
    layers: {
      happened: "The service started inside an isolated container.",
      how: "An image describes the environment; a container is a running copy of it.",
      why: "Eliminates 'works on my machine' and gives Kivo a sandbox to run generated code safely.",
      impl: "Multi-stage Dockerfile (python:3.12-slim), non-root user, healthcheck on /health.",
      tradeoffs: "Consistency and isolation vs. image build time and a daemon dependency.",
    },
  },
  "react-native": {
    id: "react-native",
    name: "React Native",
    category: "Mobile",
    what: "A framework for building native mobile apps with React.",
    whyHere: "The Tandem mobile client is React Native + Expo; auth screens are generated into it.",
    usedIn: ["Mobile App"],
    related: ["rest"],
    subtopics: ["navigation", "secure storage", "offline", "OTA updates"],
    layers: {
      happened: "The app on the phone sent a request and updated the screen.",
      how: "React components render native views; network calls use a generated typed client.",
      why: "One codebase for iOS and Android, consistent with the existing app.",
      impl: "Expo SDK, expo-secure-store for tokens, TanStack Query for requests and retries.",
      tradeoffs: "Shared code vs. occasional native-module friction.",
    },
  },
  "api-gateway": {
    id: "api-gateway",
    name: "API Gateway",
    category: "Infrastructure",
    what: "A single entry point that routes requests to backend services.",
    whyHere: "Routes /auth, /users and /notify to the right service and verifies JWTs centrally.",
    usedIn: ["API Gateway"],
    related: ["jwt", "rate-limiting"],
    subtopics: ["routing", "auth offload", "observability"],
    layers: {
      happened: "The request passed through the front door of the backend.",
      how: "The gateway looks at the path and forwards the request to the matching service.",
      why: "Clients need one address; cross-cutting concerns (auth, limits, tracing) live in one place.",
      impl: "Traefik with path-prefix routers; injects `traceparent` headers for OpenTelemetry.",
      tradeoffs: "One more hop (~1ms) vs. centralized policy.",
    },
  },
  caching: {
    id: "caching",
    name: "Caching",
    category: "Performance",
    what: "Keeping copies of expensive results so repeated reads are fast.",
    whyHere: "User profile reads are cached in Redis for 60s.",
    usedIn: ["User Management"],
    related: ["redis"],
    subtopics: ["cache-aside", "invalidation", "ttl", "stampede protection"],
    layers: {
      happened: "A saved answer was reused instead of recomputed.",
      how: "Check the cache first; on a miss, compute, store with an expiry, and return.",
      why: "Repeated identical reads were the main latency source in a past project.",
      impl: "Cache-aside with `GET`/`SETEX`; keys versioned by schema hash.",
      tradeoffs: "Speed vs. staleness and invalidation complexity.",
    },
  },
  "db-index": {
    id: "db-index",
    name: "Database index",
    category: "Database",
    what: "A data structure that makes finding rows fast.",
    whyHere: "`users.email` is indexed so login lookups stay ~1ms regardless of user count.",
    usedIn: ["Authentication"],
    related: ["postgresql"],
    subtopics: ["b-tree", "composite indexes", "covering indexes"],
    layers: {
      happened: "The database found the user instantly instead of scanning every row.",
      how: "Like a book index: sorted keys pointing to row locations.",
      why: "Login is the most frequent query on this table.",
      impl: "Unique B-tree index on lower(email).",
      tradeoffs: "Faster reads vs. slightly slower writes and extra storage.",
    },
  },
  transactions: {
    id: "transactions",
    name: "Transactions",
    category: "Database",
    what: "Grouping database operations so they all succeed or all fail.",
    whyHere: "Password reset updates the hash and invalidates tokens in one transaction.",
    usedIn: ["Authentication", "Payments"],
    related: ["postgresql"],
    subtopics: ["ACID", "isolation levels", "deadlocks"],
    layers: {
      happened: "Several changes were saved together as one unit.",
      how: "BEGIN … COMMIT; if anything fails, ROLLBACK undoes everything.",
      why: "A half-applied reset could leave old sessions valid.",
      impl: "`async with session.begin():` in SQLAlchemy.",
      tradeoffs: "Correctness vs. lock contention under heavy concurrency.",
    },
  },
  stripe: {
    id: "stripe",
    name: "Stripe",
    category: "External service",
    what: "A payments platform with APIs for charging cards and managing subscriptions.",
    whyHere: "Proposed for the Payments service.",
    usedIn: ["Payments"],
    related: ["webhooks", "idempotency"],
    subtopics: ["payment intents", "webhooks", "idempotency keys", "test mode"],
    layers: {
      happened: "A payment was handed to Stripe to process.",
      how: "The server creates a PaymentIntent; the app confirms it; Stripe calls back with the result.",
      why: "Handling card data directly would require PCI compliance.",
      impl: "stripe-python, idempotency keys per order, signed webhook verification.",
      tradeoffs: "Fast integration vs. per-transaction fees and vendor coupling.",
    },
  },
}

export function concept(id?: string) {
  return id ? CONCEPTS[id] : undefined
}
